# Site settings
title: Addidé
email: post@addide.no
url: https://addide.no
description: "Fellesverksted for 3D printing i Mandal"
taglong: ""
tagshort: ""
skills: "3D Modellering - 3D Printing - Etterbehandling"
repo: https://github.com/addide-makerspace/addide.github.io

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 039BE5 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  location: Lokasjon
  social: Sosiale medier

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: 'https://www.facebook.com/people/Addidé-Mandal/100090323092179/'
  - title: instagram
    url: 'https://www.instagram.com/lindesnesregionen_naringshage/'
  - title: github
    url: 'https://github.com/Addide-makerspace'

# Postal address (add as many lines as necessary)
address:
  - line: Hollendergata 3
  - line: 4514, Mandal

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

cloudinary:
  cloud_name: <det9ftymo>
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"

plugins:
  - jekyll-responsive-image
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap